simr: an R Package for Power Analysis of Linear Mixed Models by Simulation
========================================================

Simplified version of the paper, with the R excerpts.

```{r knitr, echo=FALSE}
library(knitr)
opts_knit$set(root.dir = "..")
opts_chunk$set(dev=c("svg", "png", "pdf"))
```

```{r load, message=FALSE}
library(devtools)
load_all(export_all=FALSE)
```


```{r options, echo=FALSE, message=FALSE}
simrOptions(nSim=25, progress=FALSE)
```

Example Data
------------

```{r example, echo=FALSE}
fgcol <- c(a=simr:::lcrgreen, b=simr:::lcrblue, c=simr:::lcrbrown)
bgcol <- simr:::lighten(fgcol)
plot(example$x, example$z,
    #ylim = c(0, 20),
    #lwd = 2,
    pch = 21,
    col = fgcol[example$g],
    bg = bgcol[example$g],
    cex.lab = 2
    )
#tmp <- mapply(abline, 10+unique(example$z), -1/4, col=fgcol, lty=4)
```

Tutorial One
------------

Post-hoc power analyses.

```{r powersim1}
model1 <- glmer(z ~ x + (1|g), family="poisson", data=example)
summary(model1)

powerSim(model1)
```

Tutorial Two
------------

Calculate a power curve.

```{r powercurve1}
pc1 <- powerCurve(model1)
print(pc1)
plot(pc1)
```

Tutorial Three
--------------

Specify the sample and effect sizes.

```{r fixef1}
fixef(model1)
fixef(model1)["x"]
```

```{r fixef2}
model2 <- model1
fixef(model2)["x"] <- -0.05
```

```{r powercurve2}
pc2 <- powerCurve(model2)
print(pc2)
plot(pc2)
```

```{r powercurve3}
model3 <- extend(model2, along="x", n=20)
pc3 <- powerCurve(model3)
print(pc3)
plot(pc3)
```

Tutorial Four
-------------

We can have different values for alpha.

```{r powercurve3multi}
plot(pc3, pval=c(0.01, 0.05, 0.10))
```

Tutorial Five
-------------

Extend another dimension.

```{r powercurve4}
model4 <- extend(model2, along="g", n=15)
pc4 <- powerCurve(model4, along="g")
print(pc4)
plot(pc4)
plot(pc4, pval=c(0.01, 0.05, 0.10))
```
